### ISSUE TITLE
hide_menus() in jquery.filebrowser.js assumes that jQuery UI is installed

### ISSUE THREAD

**Issue by slbayer** [jcubic/jquery.filebrowser#2]
This is an infelicity more than a bug, but the hide_menus() function in jquery.filebrowser.js assumes that the jQuery menu() function is defined, so a TypeError is thrown every time hide_menus() is called if jQuery UI isn't provided.

**Comment by jcubic** [comment]
If you don't have jQuery UI you should not use menus, that's requirement. Why would you use `hide_menus()` if you don't have menus?

Is this function called when you do some action? Where are no `contextmenu` options set?
