### ISSUE TITLE
Uncaught TypeError: X.when.appy is not a function

### ISSUE THREAD

**Issue by merlobranco** [jcubic/jquery.filebrowser#4]
Hello guys thank you for such as incredible library.
The thing is triggering the error mentioned on the title **(on a dragging file event)**.

SOLUTION:

Replace **$.when.appy** by **$.when.apply**

The following piece of code:

promise = **$.when.appy**($, selected[settings.name].map(function(src) {
                            var dest = self.join(new_path, self.split(src).pop());
                            if (!same_root(self, src, dest)) {
                                return self._rename(src, dest);
                            }
                        }));

Should be

promise = **$.when.apply**($, selected[settings.name].map(function(src) {
                            var dest = self.join(new_path, self.split(src).pop());
                            if (!same_root(self, src, dest)) {
                                return self._rename(src, dest);
                            }
                        }));

**Comment by jcubic** [comment]
Thanks for the report, can you add a fix. This should be easy since you already found the solution to the error.

**Comment by merlobranco** [comment]
Done.
