### ISSUE TITLE
callback function for open directory?

### ISSUE THREAD

**Issue by nbao** [jcubic/jquery.filebrowser#7]
Hello,
It works great but I have problems with subfolders and large files. I have a php backend, it loads all the sub directory and files. it will block if there are too many files. I think it would be better if I could ajax get the file for every click on the folder.
Is there a callback when we double click on the folder? 
It will be better if there is callback function background for directory onReady it will call ajax for each directory in current directory.

**Comment by jcubic** [comment]
Do you mean that you have thousands of files in a single directory and the browser is slowing down? The way it works now is that the library doesn't care what is the content of the files and it loads only a single directory at once.

I'm not sure what the problem you have is, can you maybe create a reproduction of the issue or share your working code? If you can't expose your code you can send it to my email I can check out what the problem is.

**Comment by nbao** [comment]
Yes exactly i use the code https://codepen.io/jcubic/pen/aBKYRR to load all files
You can check here 
https://git.drupalcode.org/project/link_filebrowser/-/blob/1.0.0/js/filebrowser-block.js
Backend with drupal
https://git.drupalcode.org/project/link_filebrowser/-/blob/1.0.0/src/Controller/LinkFileBrowserController.php
method public function scan($dir) it will get all files. It works for test with under 500 files
I think there is a way to make it load files better on 2 levels if it checks the directory it will call ajax to load. it will callback automatically to get sub folder
```javascript
} else if ($.isPlainObject(dir[key])) {
                    result.dirs.push(key);
                  }
```

**Comment by jcubic** [comment]
But you can do this with the current API, just look at the readme:

```javascript
$(function() {
    var browse = $('#browser').browse({
        root: '/',
        separator: '/',
        contextmenu: true,
        dir: function(path) {
            $.get(`/dir?path=${path}`);
        },
        open: function(filename) {
            console.log('opening ' + filename);
        }
    });
});
```

**Comment by nbao** [comment]
thanks, i think it works with ajax load current path, it takes time to request from server every click.

**Comment by nbao** [comment]
there is error if folder is empty
jquery.filebrowser.js?v=9.5.9:571 Uncaught TypeError: $menu.menu is not a function
    at HTMLDivElement.<anonymous> (jquery.filebrowser.js?v=9.5.9:571:31)
Line : 571
    https://github.com/jcubic/jquery.filebrowser/blob/master/js/jquery.filebrowser-0.8.4.js

     var $menu = make_menu(context_menu_object.menu).appendTo('body');
     if($menu){
                        $menu.menu();
                        var offset = $content.offset();
                        $menu.css({
                            left: e.pageX,
                            top: e.pageY
                        });
    }
                        return false;

**Comment by jcubic** [comment]
Again can you share your working code? This is not helpful.

Here is the FS demo that allows creation of empty directories

https://jcubic.github.io/wayne/fs/

so the bug is probably in your code. I will not be able to debug your code if you don't show it.

**Comment by jcubic** [comment]
I think that what you're trying to do is to use contexmenu without including jQuery UI. I have nothing to do with empty directory.

**Comment by jcubic** [comment]
If you still have a problem create another issue.

**Comment by nbao** [comment]
My work is on drupal https://www.drupal.org/project/link_filebrowser/
I create static html and Js it works but when I use ajax it doesn't work with empty directory. I guess Php returns array[] but js needs {} object. I change the algorithm for loading subdirectory files at 2 levels of recusive. because if i use ajax directly when clicking on folder icon its not smooth (or it have to chane icone folder to spinner on ajax load, i don't know how to do that)

**Comment by jcubic** [comment]
You should be able to add spinner on your own in CSS, by adding a class to the div element.

```javascript
dir: async function(dirname) {
   $('.browser-widget').addClass('loading');
   const content = await $.get(`/backend?path=${dirname}`);
   $('.browser-widget').removeClass('loading');
   return content;
}
```

and you can add spinner in CSS pseudo element:

```css
.browser-widget.loading .content::before {
   
}
```

I can add loading class and spinner to the library, but you can do that in your own code.
